---
# tasks file for mongodebian
 - name: add MongoDB GPG key
   apt_key:
     keyserver: keyserver.ubuntu.com
     id: 4B7C549A058F8B6B
 - apt_repository:
     repo: deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.2 multiverse
     state: present
     filename: mongodb-org-4.2.list
 - name: Update repositories cache and install "mongodb" package
   apt:
     name:
       [
         "mongodb-org",
         "python-pip"
       ]
     state: present
     allow_unauthenticated: yes
     update_cache: true

 - name: Install Pymongo
   shell: python -m pip install pymongo
   args:
     executable: /bin/bash

 - name: Ensure group "mongodb" exists
   group:
     name: mongodb
     state: present
 - name: Create MongoDB User and Group
   user:
     name: mongodb
     groups: mongodb
 - name: create data directory
   file:
      path: "{{ mongodb_db_path }}"
      mode: 0755
      owner: mongodb
      group: mongodb
      state: directory
 - name: remove a file
   file:
     path: /etc/mongod.conf
     state: absent
 - name: mongo Keyfile
   template:
     src: keyfile.j2
     dest: "{{ mongodb_key_file }}"
     owner: mongodb
     group: mongodb
     mode: 0400
 - name: mongo conf copy
   template:
     src: mongod.conf.j2
     dest: /etc/mongod.conf
     owner: root
     group: root
     mode: 0644
   notify:
     - start mongodb server

 - name: Enable service MongoDB, and start service
   service:
     name: mongod
     enabled: yes
     state: started
